### ISSUE TITLE
only replay-protected (EIP-155) transactions allowed over RPC

### ISSUE THREAD

**Issue by ZeynabKhani** [gnosis/safe-contract-deployment-replay#5]
Hi there,
I tried to retrieve my funds which I accidentally sent to my Safe account on BSC main net. I tried to use this script to deploy the ProxyFactory on BSC main net at this address 0x76e2cfc1f5fa8f6a5b3fc4c8f4788f0116861f9b. When I run `yarn deploy` on BSC main net I get the error "Deployment account has been used on this network". 
I tried to comment this part because the account was used once but not for deploying this contract. Then I get this error: 
`Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":48,\"error\":{\"code\":-32000,\"message\":\"only replay-protected (EIP-155) transactions allowed over RPC\"}}"`
Searching about this error I found that it gets resolved by specifying the chainId. But since this script uses a signed transaction to deploy the contract, I can not find a way to do this.
Any suggestions?
Thank you in advance.

**Comment by rmeissner** [comment]
It is not possible to run this script on BSC, as the deployment account was used for a different contract, therefore it is not possible to get the same address.
